-- 0001_init.sql — Sanalys initial schema.
--
-- The CREATE TABLE section below is generated by drizzle-kit from src/schema/*.ts.
-- Everything after the INVARIANTS banner is written by hand, because a Drizzle schema
-- cannot express it: the chair EXCLUDE constraint, the triggers, the public availability
-- view and the three Postgres roles (docs/03-DATOS.md sections 3.3, 4 and 6).
--
-- Re-generating the schema never rewrites this file: drizzle-kit writes a new numbered
-- migration and does not know about the hand-written half (G-026).

CREATE EXTENSION IF NOT EXISTS btree_gist;--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_uuidv7;--> statement-breakpoint
CREATE TYPE "public"."caja_tipo" AS ENUM('INGRESO', 'EGRESO', 'CIERRE');--> statement-breakpoint
CREATE TYPE "public"."insumo_tipo" AS ENUM('solucion', 'puro', 'unidad');--> statement-breakpoint
CREATE TYPE "public"."lead_etapa" AS ENUM('nuevos', 'seguimiento', 'presupuesto', 'ganado', 'perdido');--> statement-breakpoint
CREATE TYPE "public"."turno_estado" AS ENUM('PENDIENTE', 'CONFIRMADO', 'ESPERA', 'PAGADO', 'TRATAMIENTO', 'FINALIZADO', 'CUMPLIDO', 'AUSENTE', 'CANCELADO');--> statement-breakpoint
CREATE TABLE "salas" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"nombre" text NOT NULL,
	"tipo" text NOT NULL,
	"capacidad" integer DEFAULT 1 NOT NULL,
	"profesional_id" uuid,
	"horarios" jsonb,
	"bloqueos" jsonb,
	"activa" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "salas_tipo_valido" CHECK ("salas"."tipo" in ('consulta', 'sueros')),
	CONSTRAINT "salas_capacidad_minima" CHECK ("salas"."capacidad" >= 1)
);
--> statement-breakpoint
CREATE TABLE "turnos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid,
	"paciente_nombre" text NOT NULL,
	"dni" text,
	"telefono" text,
	"email" text,
	"servicio" text,
	"motivo" text,
	"sala_id" uuid NOT NULL,
	"puesto" integer DEFAULT 1 NOT NULL,
	"inicio" timestamp with time zone NOT NULL,
	"fin" timestamp with time zone NOT NULL,
	"duracion_min" integer GENERATED ALWAYS AS ((extract(epoch from (fin - inicio)) / 60)::int) STORED,
	"estado" "turno_estado" DEFAULT 'PENDIENTE' NOT NULL,
	"notas" text,
	"profesional_id" uuid,
	"medica" text,
	"origen" text DEFAULT 'sistema' NOT NULL,
	"hora_inicio_infusion" timestamp with time zone,
	"registro_ref_id" uuid,
	"formula_nombre" text,
	"duracion_real_min" integer,
	"email_enviado_at" timestamp with time zone,
	"email_error" text,
	"cancelado_motivo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "turnos_fin_posterior" CHECK ("turnos"."fin" > "turnos"."inicio"),
	CONSTRAINT "turnos_puesto_minimo" CHECK ("turnos"."puesto" >= 1),
	CONSTRAINT "turnos_origen_valido" CHECK ("turnos"."origen" in ('sistema', 'web'))
);
--> statement-breakpoint
CREATE TABLE "caja_movimientos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"ticket_id" uuid,
	"nro_comp" text NOT NULL,
	"tipo" "caja_tipo" NOT NULL,
	"det" text,
	"monto" numeric(12, 2) NOT NULL,
	"medio" text NOT NULL,
	"dni" text,
	"fecha" timestamp with time zone NOT NULL,
	"usuario" text,
	"profesional" text,
	"centro_costo" text,
	"honorario_calculado" numeric(12, 2),
	"es_honorario" boolean DEFAULT false NOT NULL,
	"es_traspaso" boolean DEFAULT false NOT NULL,
	"destino" text,
	"anulado" boolean DEFAULT false NOT NULL,
	"motivo_anulacion" text,
	"anulado_por" text,
	"anulado_at" timestamp with time zone,
	"periodo" char(7) NOT NULL,
	"arqueo" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "caja_monto_positivo" CHECK ("caja_movimientos"."monto" > 0),
	CONSTRAINT "caja_periodo_formato" CHECK ("caja_movimientos"."periodo" ~ '^[0-9]{4}-[0-9]{2}$')
);
--> statement-breakpoint
CREATE TABLE "comprobantes_seq" (
	"prefijo" text NOT NULL,
	"anio" integer NOT NULL,
	"ultimo" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "comprobantes_seq_prefijo_anio_pk" PRIMARY KEY("prefijo","anio")
);
--> statement-breakpoint
CREATE TABLE "inversiones" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"descripcion" text NOT NULL,
	"tipo" text,
	"entidad" text,
	"fecha_inicio" date,
	"fecha_venc" date,
	"capital" numeric(12, 2),
	"valor_actual" numeric(12, 2),
	"estado" text,
	"notas" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "periodos_cerrados" (
	"periodo" char(7) PRIMARY KEY NOT NULL,
	"cerrado_por" text,
	"cerrado_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saldos_iniciales" (
	"periodo" char(7) PRIMARY KEY NOT NULL,
	"monto" numeric(12, 2) NOT NULL,
	"usuario" text,
	"fecha" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consentimiento_textos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"tipo_slug" text NOT NULL,
	"tipo_nombre" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"texto" text NOT NULL,
	"vigente" boolean DEFAULT true NOT NULL,
	"creado_por" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "consentimientos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid,
	"paciente_nombre" text NOT NULL,
	"dni" text,
	"tipo_slug" text NOT NULL,
	"texto_version_id" uuid NOT NULL,
	"medica" text,
	"alergias" text,
	"checklist" jsonb,
	"firmado" boolean DEFAULT false NOT NULL,
	"firma_r2_key" text,
	"firma_sha256" text,
	"firmado_at" timestamp with time zone,
	"ip" "inet",
	"user_agent" text,
	"registrado_por" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lead_bitacora" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"lead_id" uuid NOT NULL,
	"f" timestamp with time zone DEFAULT now() NOT NULL,
	"t" text NOT NULL,
	"tipo" text DEFAULT 'neutro' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lead_bitacora_tipo_valido" CHECK ("lead_bitacora"."tipo" in ('positivo', 'negativo', 'neutro'))
);
--> statement-breakpoint
CREATE TABLE "leads" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"nombre" text NOT NULL,
	"tel" text,
	"origen" text,
	"etapa" "lead_etapa" DEFAULT 'nuevos' NOT NULL,
	"interes" text,
	"proximo_contacto" date,
	"convertido" boolean DEFAULT false NOT NULL,
	"motivo" text,
	"paciente_id" uuid,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "registro_materiales" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"registro_id" uuid NOT NULL,
	"insumo_id" uuid NOT NULL,
	"cantidad" numeric(10, 3) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "registros_enfermeria" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid,
	"turno_id" uuid,
	"enfermera" text,
	"estado" text DEFAULT 'EN CURSO' NOT NULL,
	"inicio" timestamp with time zone NOT NULL,
	"fin" timestamp with time zone,
	"signos" jsonb,
	"via_tipo" text,
	"via_calibre" text,
	"formula_id" uuid,
	"formula_nombre" text,
	"lote" text,
	"duracion_min" integer,
	"observaciones" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "registros_estado_valido" CHECK ("registros_enfermeria"."estado" in ('EN CURSO', 'FINALIZADO'))
);
--> statement-breakpoint
CREATE TABLE "archivos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid NOT NULL,
	"nombre" text NOT NULL,
	"r2_key" text NOT NULL,
	"mime" text,
	"bytes" integer,
	"fecha_subida" timestamp with time zone,
	"subido_por" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "bitacora" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid NOT NULL,
	"creado" timestamp with time zone DEFAULT now() NOT NULL,
	"autor" text,
	"etiquetas" jsonb,
	"comentario" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "evoluciones" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid NOT NULL,
	"fecha" timestamp with time zone NOT NULL,
	"medico" text,
	"tipo" text,
	"peso" numeric(6, 2),
	"talla" numeric(5, 1),
	"imc" numeric(5, 1),
	"ta" text,
	"fc" integer,
	"sat" integer,
	"cin" numeric(5, 1),
	"cad" numeric(5, 1),
	"icc" numeric(4, 2),
	"motivo" text,
	"diagnostico" text,
	"plan" text,
	"notas" text,
	"detalle" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pacientes" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"nombre" text NOT NULL,
	"dni" text NOT NULL,
	"dni_normalizado" text GENERATED ALWAYS AS (regexp_replace(dni, '[^0-9]', '', 'g')) STORED,
	"fecha_nac" date,
	"sexo" text DEFAULT 'F',
	"tel" text,
	"email" text,
	"loc" text,
	"alergias" text,
	"obra_social" text,
	"contacto_emergencia" text,
	"tel_emergencia" text,
	"hc_dieta" text DEFAULT 'Omnivora',
	"hc_ayuno" integer,
	"hc_tox_tabaco" boolean,
	"hc_tox_alcohol" boolean,
	"hc_tox_otros" boolean,
	"hc_antecedentes" text,
	"hc_expectativas" text,
	"perfil_profesion" text,
	"perfil_canal" text,
	"perfil_recomendado_por" text,
	"perfil_alerta" text,
	"perfil_notas" text,
	"seguridad" jsonb,
	"activo" boolean DEFAULT true NOT NULL,
	"fecha_alta" timestamp with time zone,
	"creado_por" text,
	"origen_crm" text,
	"interes_crm" text,
	"crm_lead_id" uuid,
	"ultima_modificacion" timestamp with time zone,
	"modificado_por" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "planes" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"paciente_id" uuid NOT NULL,
	"nombre" text NOT NULL,
	"sesiones" integer,
	"sesiones_usadas" integer DEFAULT 0 NOT NULL,
	"costo_total" numeric(12, 2),
	"pagado" numeric(12, 2) DEFAULT '0' NOT NULL,
	"saldo_pendiente" numeric(12, 2) DEFAULT '0' NOT NULL,
	"validez_dias" integer,
	"fecha_vencimiento" date,
	"es_presupuesto" boolean DEFAULT false NOT NULL,
	"estado" text,
	"items" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "auditoria" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"ts" timestamp with time zone DEFAULT now() NOT NULL,
	"usuario_id" uuid,
	"usuario" text,
	"accion" text NOT NULL,
	"detalle" text,
	"tabla" text,
	"fila_id" uuid,
	"antes" jsonb,
	"despues" jsonb
);
--> statement-breakpoint
CREATE TABLE "config" (
	"clave" text PRIMARY KEY NOT NULL,
	"valor" jsonb NOT NULL,
	"actualizado_por" text,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "novedades" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"slug" text NOT NULL,
	"titulo" text NOT NULL,
	"resumen" text,
	"cuerpo_md" text NOT NULL,
	"autora_persona_id" uuid NOT NULL,
	"publicada" boolean DEFAULT false NOT NULL,
	"publicada_at" timestamp with time zone,
	"actualizada_at" timestamp with time zone,
	"portada_r2_key" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "novedades_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "rate_limits" (
	"key" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "rate_limits_key_window_start_pk" PRIMARY KEY("key","window_start")
);
--> statement-breakpoint
CREATE TABLE "formula_componentes" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"formula_id" uuid NOT NULL,
	"insumo_id" uuid NOT NULL,
	"dosis" numeric(10, 3) NOT NULL,
	"unidad" text,
	"ml_equivalente" numeric(10, 3),
	"costo" numeric(12, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "formulas" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"nombre" text NOT NULL,
	"pvp" numeric(12, 2),
	"vol_total" numeric(10, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "insumos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"nombre" text NOT NULL,
	"lab" text,
	"tipo" "insumo_tipo" NOT NULL,
	"concentracion" numeric(6, 2),
	"vol_por_vial" numeric(10, 3),
	"unidad_vial" text,
	"unidad_uso" text,
	"stock_disp" numeric(12, 3) DEFAULT '0' NOT NULL,
	"stock_disp_ml" numeric(12, 3),
	"costo" numeric(12, 2),
	"lote" text,
	"fecha_vencimiento" date,
	"minimo_viales" numeric(10, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "insumos_nombre_unique" UNIQUE("nombre"),
	CONSTRAINT "insumos_stock_no_negativo" CHECK ("insumos"."stock_disp" >= 0)
);
--> statement-breakpoint
CREATE TABLE "pedidos" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"tipo" text NOT NULL,
	"medica" text,
	"items" integer,
	"detalle" text,
	"usuario" text,
	"creado" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "pedidos_tipo_valido" CHECK ("pedidos"."tipo" in ('RECETA MÉDICA', 'ORDEN PROVEEDOR'))
);
--> statement-breakpoint
CREATE TABLE "personas" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"nombre" text NOT NULL,
	"dni" text,
	"tel" text,
	"email" text,
	"especialidad" text,
	"matricula" text,
	"es_medica" boolean DEFAULT false NOT NULL,
	"pct_medica_individual" numeric(5, 2),
	"es_socia" boolean DEFAULT false NOT NULL,
	"parte_sociedad" numeric(5, 2),
	"activo" boolean DEFAULT true NOT NULL,
	"tipo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "personas_pct_medica_rango" CHECK ("personas"."pct_medica_individual" is null or ("personas"."pct_medica_individual" >= 0 and "personas"."pct_medica_individual" <= 100)),
	CONSTRAINT "personas_parte_sociedad_rango" CHECK ("personas"."parte_sociedad" is null or ("personas"."parte_sociedad" >= 0 and "personas"."parte_sociedad" <= 100))
);
--> statement-breakpoint
CREATE TABLE "usuarios" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"clerk_user_id" text NOT NULL,
	"email" text NOT NULL,
	"nombre" text NOT NULL,
	"rol" text DEFAULT 'operativo' NOT NULL,
	"permisos" text[] DEFAULT '{}'::text[] NOT NULL,
	"activo" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "usuarios_clerk_user_id_unique" UNIQUE("clerk_user_id"),
	CONSTRAINT "usuarios_email_unique" UNIQUE("email"),
	CONSTRAINT "usuarios_rol_valido" CHECK ("usuarios"."rol" in ('admin', 'operativo')),
	CONSTRAINT "usuarios_permisos_validos" CHECK ("usuarios"."permisos" <@ array['admin','pacientes','stock','formulas','caja','balance','agenda','enfermeria','sueros','legal','crm']::text[])
);
--> statement-breakpoint
ALTER TABLE "salas" ADD CONSTRAINT "salas_profesional_id_personas_id_fk" FOREIGN KEY ("profesional_id") REFERENCES "public"."personas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turnos" ADD CONSTRAINT "turnos_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turnos" ADD CONSTRAINT "turnos_sala_id_salas_id_fk" FOREIGN KEY ("sala_id") REFERENCES "public"."salas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turnos" ADD CONSTRAINT "turnos_profesional_id_personas_id_fk" FOREIGN KEY ("profesional_id") REFERENCES "public"."personas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consentimientos" ADD CONSTRAINT "consentimientos_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consentimientos" ADD CONSTRAINT "consentimientos_texto_version_id_consentimiento_textos_id_fk" FOREIGN KEY ("texto_version_id") REFERENCES "public"."consentimiento_textos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lead_bitacora" ADD CONSTRAINT "lead_bitacora_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registro_materiales" ADD CONSTRAINT "registro_materiales_registro_id_registros_enfermeria_id_fk" FOREIGN KEY ("registro_id") REFERENCES "public"."registros_enfermeria"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registro_materiales" ADD CONSTRAINT "registro_materiales_insumo_id_insumos_id_fk" FOREIGN KEY ("insumo_id") REFERENCES "public"."insumos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registros_enfermeria" ADD CONSTRAINT "registros_enfermeria_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registros_enfermeria" ADD CONSTRAINT "registros_enfermeria_turno_id_turnos_id_fk" FOREIGN KEY ("turno_id") REFERENCES "public"."turnos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "archivos" ADD CONSTRAINT "archivos_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bitacora" ADD CONSTRAINT "bitacora_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evoluciones" ADD CONSTRAINT "evoluciones_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "planes" ADD CONSTRAINT "planes_paciente_id_pacientes_id_fk" FOREIGN KEY ("paciente_id") REFERENCES "public"."pacientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "novedades" ADD CONSTRAINT "novedades_autora_persona_id_personas_id_fk" FOREIGN KEY ("autora_persona_id") REFERENCES "public"."personas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "formula_componentes" ADD CONSTRAINT "formula_componentes_formula_id_formulas_id_fk" FOREIGN KEY ("formula_id") REFERENCES "public"."formulas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "formula_componentes" ADD CONSTRAINT "formula_componentes_insumo_id_insumos_id_fk" FOREIGN KEY ("insumo_id") REFERENCES "public"."insumos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "turnos_inicio_idx" ON "turnos" USING btree ("inicio");--> statement-breakpoint
CREATE INDEX "turnos_sala_inicio_idx" ON "turnos" USING btree ("sala_id","inicio");--> statement-breakpoint
CREATE INDEX "turnos_dni_idx" ON "turnos" USING btree ("dni");--> statement-breakpoint
CREATE UNIQUE INDEX "caja_nro_comp_unico_egreso_cierre" ON "caja_movimientos" USING btree ("nro_comp") WHERE "caja_movimientos"."tipo" in ('EGRESO', 'CIERRE');--> statement-breakpoint
CREATE INDEX "caja_periodo_fecha_idx" ON "caja_movimientos" USING btree ("periodo","fecha");--> statement-breakpoint
CREATE INDEX "caja_dni_idx" ON "caja_movimientos" USING btree ("dni");--> statement-breakpoint
CREATE INDEX "caja_nro_comp_idx" ON "caja_movimientos" USING btree ("nro_comp");--> statement-breakpoint
CREATE INDEX "consentimientos_dni_idx" ON "consentimientos" USING btree ("dni");--> statement-breakpoint
CREATE INDEX "consentimientos_paciente_idx" ON "consentimientos" USING btree ("paciente_id");--> statement-breakpoint
CREATE INDEX "leads_etapa_idx" ON "leads" USING btree ("etapa");--> statement-breakpoint
CREATE INDEX "leads_proximo_contacto_idx" ON "leads" USING btree ("proximo_contacto");--> statement-breakpoint
CREATE INDEX "evoluciones_paciente_fecha_idx" ON "evoluciones" USING btree ("paciente_id","fecha" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "pacientes_dni_normalizado_key" ON "pacientes" USING btree ("dni_normalizado");--> statement-breakpoint
CREATE INDEX "pacientes_nombre_idx" ON "pacientes" USING btree ("nombre" text_pattern_ops);--> statement-breakpoint
CREATE INDEX "auditoria_ts_idx" ON "auditoria" USING btree ("ts" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "novedades_publicadas_idx" ON "novedades" USING btree ("publicada","publicada_at" DESC NULLS LAST);--> statement-breakpoint
-- =============================================================================
-- INVARIANTS — hand-written, docs/03-DATOS.md section 4
-- =============================================================================

-- Foreign keys left out of the Drizzle schema: pacientes and leads point at each other,
-- and so do turnos and registros_enfermeria. Declaring them in TypeScript makes the
-- modules circular and degrades both tables to any.
ALTER TABLE "pacientes" ADD CONSTRAINT "pacientes_crm_lead_id_leads_id_fk" FOREIGN KEY ("crm_lead_id") REFERENCES "public"."leads"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "turnos" ADD CONSTRAINT "turnos_registro_ref_id_registros_enfermeria_id_fk" FOREIGN KEY ("registro_ref_id") REFERENCES "public"."registros_enfermeria"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

-- The chair invariant. The booking transaction picks the first free puesto in
-- 1..capacidad; THIS is what guarantees two bookings never share it, not the app.
-- A CANCELADO or AUSENTE turno frees its chair. Critical test 1 of docs/11-ROADMAP.md.
ALTER TABLE "turnos" ADD CONSTRAINT "turnos_sillon_exclusivo" EXCLUDE USING gist (
  "sala_id" WITH =,
  "puesto" WITH =,
  tstzrange("inicio", "fin", '[)') WITH &&
) WHERE ("estado" NOT IN ('CANCELADO', 'AUSENTE'));--> statement-breakpoint

-- updated_at is maintained by the database, never written by the app.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$fn$;--> statement-breakpoint

DO $do$
DECLARE t record;
BEGIN
  FOR t IN
    SELECT c.table_name AS name
    FROM information_schema.columns c
    JOIN information_schema.tables x
      ON x.table_schema = c.table_schema AND x.table_name = c.table_name AND x.table_type = 'BASE TABLE'
    WHERE c.table_schema = 'public' AND c.column_name = 'updated_at'
  LOOP
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION touch_updated_at()',
      t.name || '_touch_updated_at', t.name
    );
  END LOOP;
END
$do$;--> statement-breakpoint

-- No cash movement in a closed period: the third layer of critical test 4. Zod gives the
-- message, the Server Action asserts, and this trigger is what cannot be bypassed.
CREATE OR REPLACE FUNCTION caja_periodo_abierto() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF EXISTS (SELECT 1 FROM periodos_cerrados p WHERE p.periodo = NEW.periodo) THEN
    RAISE EXCEPTION 'periodo cerrado: %', NEW.periodo USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$fn$;--> statement-breakpoint
CREATE TRIGGER caja_movimientos_periodo_insert BEFORE INSERT ON "caja_movimientos" FOR EACH ROW EXECUTE FUNCTION caja_periodo_abierto();--> statement-breakpoint
CREATE TRIGGER caja_movimientos_periodo_update BEFORE UPDATE ON "caja_movimientos" FOR EACH ROW EXECUTE FUNCTION caja_periodo_abierto();--> statement-breakpoint

-- Turno state machine (docs/03-DATOS.md section 3.3). Forward along the canonical chain,
-- out to AUSENTE or CANCELADO from any live state, and nothing leaves a terminal state.
-- CUMPLIDO is historical: only the Firestore import (unit 24) ever writes it.
-- Whether skipping a step is legitimate is OQ-12; it blocks nothing here.
CREATE OR REPLACE FUNCTION turno_estado_transicion() RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE
  cadena constant text[] := ARRAY['PENDIENTE','CONFIRMADO','ESPERA','PAGADO','TRATAMIENTO','FINALIZADO'];
  i_old int;
  i_new int;
BEGIN
  IF NEW.estado = OLD.estado THEN
    RETURN NEW;
  END IF;

  IF OLD.estado IN ('FINALIZADO','CUMPLIDO','AUSENTE','CANCELADO') THEN
    RAISE EXCEPTION 'transicion de turno no permitida: % -> %', OLD.estado, NEW.estado
      USING ERRCODE = 'check_violation';
  END IF;

  IF NEW.estado IN ('AUSENTE','CANCELADO') THEN
    RETURN NEW;
  END IF;

  i_old := array_position(cadena, OLD.estado::text);
  i_new := array_position(cadena, NEW.estado::text);

  IF i_old IS NULL OR i_new IS NULL OR i_new <= i_old THEN
    RAISE EXCEPTION 'transicion de turno no permitida: % -> %', OLD.estado, NEW.estado
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$fn$;--> statement-breakpoint
CREATE TRIGGER turnos_estado_transicion BEFORE UPDATE OF "estado" ON "turnos" FOR EACH ROW EXECUTE FUNCTION turno_estado_transicion();--> statement-breakpoint

-- A news post is signed by a named doctor with a matricula; a foreign key cannot say
-- "and that row has a matricula".
CREATE OR REPLACE FUNCTION novedades_autora_con_matricula() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM personas p
    WHERE p.id = NEW.autora_persona_id
      AND p.matricula IS NOT NULL
      AND length(btrim(p.matricula)) > 0
  ) THEN
    RAISE EXCEPTION 'la autora de una novedad debe tener matricula'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$fn$;--> statement-breakpoint
CREATE TRIGGER novedades_autora_matricula BEFORE INSERT OR UPDATE OF "autora_persona_id" ON "novedades" FOR EACH ROW EXECUTE FUNCTION novedades_autora_con_matricula();--> statement-breakpoint

-- The public site reads availability through this view and never through turnos:
-- that table carries names, DNIs, phones and e-mails (docs/03-DATOS.md section 6).
CREATE VIEW "turnos_ocupacion" AS
SELECT "sala_id", "puesto", "inicio", "fin"
FROM "turnos"
WHERE "estado" NOT IN ('CANCELADO', 'AUSENTE');--> statement-breakpoint

-- =============================================================================
-- ROLES AND GRANTS — docs/03-DATOS.md section 6
-- Passwords are NEVER set here; they are set once by hand with ALTER ROLE and kept in the
-- password manager and the Vercel env store (docs/06-SEGURIDAD.md section 6).
--
-- All three roles are created HERE, by SQL, and never from the Neon console: the console
-- grants every role it creates membership in `neon_superuser`, which inherits everything
-- and makes every grant below decorative — a console-created `sanalys_web` can read
-- `pacientes` (G-031). Creating the role from the migration also makes it possible to hand
-- the tables over to `sanalys_migrate`, which a console-created role cannot receive (G-030).
-- =============================================================================
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sanalys_migrate') THEN CREATE ROLE sanalys_migrate LOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sanalys_app') THEN CREATE ROLE sanalys_app LOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sanalys_web') THEN CREATE ROLE sanalys_web LOGIN; END IF;
END
$do$;--> statement-breakpoint

GRANT ALL ON SCHEMA public TO sanalys_migrate;--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO sanalys_app, sanalys_web;--> statement-breakpoint

-- sanalys_app: the internal system. Full DML, minus the append-only tables.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sanalys_app;--> statement-breakpoint
REVOKE UPDATE, DELETE ON "consentimientos", "bitacora", "auditoria" FROM sanalys_app;--> statement-breakpoint

-- sanalys_web: the public site. It reads what is public, writes a booking and counts its
-- own rate limits. It has no access to any clinical or money table.
GRANT SELECT ON "salas", "config", "novedades", "turnos_ocupacion" TO sanalys_web;--> statement-breakpoint
GRANT INSERT ON "turnos" TO sanalys_web;--> statement-breakpoint
GRANT SELECT ("id") ON "turnos" TO sanalys_web;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON "rate_limits" TO sanalys_web;--> statement-breakpoint

-- Handing an object to a role requires being able to SET ROLE to it. Since Postgres 16 the
-- creator of a role gets ADMIN on it but NOT the SET option, so this line is what actually
-- unlocks the transfer below (G-030). It is wrapped because it only works when this
-- migration created the role: if `sanalys_migrate` came from the Neon console, nobody here
-- can grant it and the transfer fails loudly, which is the correct outcome.
DO $do$
BEGIN
  BEGIN
    EXECUTE 'GRANT sanalys_migrate TO CURRENT_USER WITH SET TRUE';
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;
END
$do$;--> statement-breakpoint

-- drizzle-kit runs later migrations as sanalys_migrate, so it must own the objects.
DO $do$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename AS name FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('ALTER TABLE public.%I OWNER TO sanalys_migrate', r.name);
  END LOOP;
  FOR r IN SELECT viewname AS name FROM pg_views WHERE schemaname = 'public' LOOP
    EXECUTE format('ALTER VIEW public.%I OWNER TO sanalys_migrate', r.name);
  END LOOP;
  FOR r IN SELECT t.typname AS name FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typtype = 'e' LOOP
    EXECUTE format('ALTER TYPE public.%I OWNER TO sanalys_migrate', r.name);
  END LOOP;
END
$do$;
