/** Every table in one place; drizzle-kit reads `src/schema/*.ts`. */
export * from "./agenda.ts"
export * from "./caja.ts"
export * from "./columns.ts"
export * from "./consentimientos.ts"
export * from "./crm.ts"
export * from "./enfermeria.ts"
export * from "./enums.ts"
export * from "./pacientes.ts"
export * from "./sistema.ts"
export * from "./stock.ts"
export * from "./usuarios.ts"
